<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.baiwa.th.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.baiwa.th.com" xmlns:intf="http://ws.baiwa.th.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://ws.baiwa.th.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="ecxiseSystemDate">
    <complexType/>
   </element>
   <element name="ecxiseSystemDateResponse">
    <complexType>
     <sequence>
      <element name="ecxiseSystemDateReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="ecxiseSystemDateResponse">

      <wsdl:part element="impl:ecxiseSystemDateResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="ecxiseSystemDateRequest">

      <wsdl:part element="impl:ecxiseSystemDate" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="CurrentDate">

      <wsdl:operation name="ecxiseSystemDate">

         <wsdl:input message="impl:ecxiseSystemDateRequest" name="ecxiseSystemDateRequest">

       </wsdl:input>

         <wsdl:output message="impl:ecxiseSystemDateResponse" name="ecxiseSystemDateResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="CurrentDateSoapBinding" type="impl:CurrentDate">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="ecxiseSystemDate">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="ecxiseSystemDateRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="ecxiseSystemDateResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="CurrentDateService">

      <wsdl:port binding="impl:CurrentDateSoapBinding" name="CurrentDate">

         <wsdlsoap:address location="http://150.95.24.42:8080/SystemCurrentDate/services/CurrentDate"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
