CREATE TABLE Z_MOCK_EMPLOYEE (
  EMP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  SALARY DECIMAL,
  WORKING_DATE DATE,
  IS_DELETED VARCHAR(1) DEFAULT 'N',
  CREATED_BY VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
  CREATED_DATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(20),
  UPDATED_DATE DATE
);