INSERT INTO Z_MOCK_EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY, WORKING_DATE) VALUES ('Emp1', 'LastName1', 12000, CURRENT_TIMESTAMP);
INSERT INTO Z_MOCK_EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY, WORKING_DATE) VALUES ('Emp2', 'LastName2', 24000, CURRENT_TIMESTAMP);
INSERT INTO Z_MOCK_EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY, WORKING_DATE) VALUES ('Emp3', 'LastName3', 36000, CURRENT_TIMESTAMP);
